# Generated by Django 4.1.2 on 2022-11-13 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_alter_userprofile_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.adminprofile'),
        ),
    ]
