# Generated by Django 4.1.2 on 2022-11-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_business_adminprofile_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='business',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='business',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business', verbose_name='Negocio'),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.adminprofile', verbose_name='Creado por'),
        ),
    ]
